name: MCPets
main: fr.nocsy.mcpets.MCPets
version: 1.0.0
description: More info at MCModels.net
depends:
  - MythicMobs
  - ModelEngine
softdepend:
  - WorldGuard
author: Nocsy
api-version: 1.16
commands:
  mcpets:
    description: Command to manage your pets
    Usage: /mcpets
    permission: mcpets.use
    aliases: [ pets ]